apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-website
  namespace: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: weather-website
        image: alexunger/weatherwebsite:latest
---
apiVersion: v1
kind: Service
metadata:
  name: ww-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001